-- 已合并到仓库根目录 scripts/init_database.sql（全库唯一维护的初始化脚本）。
-- 请执行：
--   mysql -h HOST -u USER -p YOUR_DATABASE < ../../scripts/init_database.sql
-- 或使用：python scripts/init_database.py（读取 partner/.env 中的 DATABASE_URL）
